name: Build this project using Pygbag
on:
  push:
    branches:
      - main

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: build
        run: |
          echo "Installing pygbag"
          python3 -m pip install pygbag
          echo "pygbag success!"
          echo "building the project"
          python3 -m pygbag --build $GITHUB_WORKSPACE/main.py
          echo "DONE"
          zip -j -r pythumbpad_demo.zip build/web

      - name: Generate Git Tag
        id: generate_tag
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="1.0"

          # Fetch all tags from the remote repository
          git fetch --tags

          # Get the latest patch version for the given major.minor version
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          
          if [ $? -ne 0 ]; then
            echo "Failed to retrieve the latest patch version."
            VERSION_PATCH=0
          fi

          # Increment the patch version or start at 0 if none exists
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi

          PYPI_TAG="${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          NEW_TAG="${VERSION_PREFIX}${PYPI_TAG}"

          echo "Generated new tag: $NEW_TAG"
          echo "Generated new PYPI tag: $PYPI_TAG"

          # Set environment variables for use in later steps
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "PYPI_TAG=$PYPI_TAG" >> $GITHUB_ENV

          # Replace VERSION_PLACEHOLDER in setup.py with the new version
          sed -i "s/{{VERSION_PLACEHOLDER}}/${PYPI_TAG}/g" setup.py

      - name: Build package
        run: python3 setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_CREDENTIALS }}
          tag: ${{ $NEW_TAG }}
          artifacts: pythumbpad_demo.zip
